[project]
name = "kubeflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kserve>=0.15.2",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pyjwt>=2.10.1",
    "scikit-learn>=1.7.1",
    "torch>=2.8.0",
]
