apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  namespace: kserve-model
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
